#!/usr/bin/sh

alias echo='echo -e'

# Some basic information
readonly PROGRAM_NAME="$(basename $0)"
readonly COMPLETE_ARGS_LIST="$@"
readonly VERSION="0.0.6"

readonly program_cache="${HOME}/.cache/${PROGRAM_NAME}"
readonly aur_package_list="${program_cache}/package_list"

# Colours
readonly LIGHT_RED='\e[1;31m'
readonly BLUE='\e[1m\e[0;36m'
readonly RESET_CLR='\e[0m'
readonly BOLD='\e[1m'
readonly ITALIC='\e[3m'

readonly ERROR="${BOLD}${LIGHT_RED}error:${RESET_CLR}"
readonly WARNING="${LIGHT_RED}warning:${RESET_CLR}"

display_help_message() {
    echo "Usage:  ${PROGRAM_NAME} <operation> [...]"
    echo "Operations:"
    echo "   ${PROGRAM_NAME} install   <package(s)>"
}

initialization_and_sanitization() {
    if ! ping archlinux.org -c 1 &> /dev/null; then
        echo "${ERROR} https://archlinux.org is unreachable"
        exit 1
    fi

    [[ -d ${program_cache} ]] || mkdir ${program_cache}

    # Execute function in the background
    [[ -f ${aur_package_list} ]] || update_aur_package_list &
}

update_aur_package_list() {
    [[ $1 == "v" ]] && echo "==> Downloading list of AUR packages..."
    curl -o ${aur_package_list}.gz -L https://aur.archlinux.org/packages.gz &>/dev/null

    [[ $1 == "v" ]] && echo "==> Unzipping compressed file..."
    gunzip < ${aur_package_list}.gz > ${aur_package_list}

    [[ $1 == "v" ]] && echo "==> Removing compressed file..."
    rm -f ${aur_package_list}.gz

    [[ $1 == "v" ]] && echo "==> Removing comments from unzipped file..."
    sed '/^#/d' -i ${aur_package_list}
}

search_packages_in_aur() {
    declare results=$(grep "$@" ${aur_package_list})

    while IFS= read -r pkg; do
        echo "${BLUE}aur/${RESET_CLR}${BOLD}${pkg}${RESET_CLR}"
    done <<< "${results}"

    return 0
}

install_aur_package() {
    declare -r pkg=$1
    declare install_location=${program_cache}/${pkg}

    if ! grep -w "^${pkg}$" ${aur_package_list} &> /dev/null; then
        echo "${ERROR} package does not exist in aur"
        exit 1
    fi

    # If the process is killed, remove the package
    trap "rm -rf ${install_location}; echo \"\n\n${ERROR} aborted by user; exiting...\";
    exit" SIGTERM SIGINT SIGHUP

    echo "---> Downloading package '${pkg}'...\n"
    git clone https://aur.archlinux.org/${pkg}.git ${install_location} &>/dev/null

    cd ${install_location}

    echo -n "${BOLD}>>> Read PKGBUILD?${RESET_CLR} "
    echo -En '[Y\n] '
    read ans
    if [[ ! ${ans} == "n" && ! ${ans} == "N" ]]; then
        ${PAGER} ./PKGBUILD
    fi

    echo -n ">${BOLD}>> Build package?${RESET_CLR} "
    echo -En '[Y\n] '

    read ans
    if [[ ! ${ans} == "n" && ! ${ans} =~ "N" ]]; then
        if makepkg --install --syncdeps --rmdeps; then
            echo "\n---> '${pkg}' was successfully installed"
        else
            echo "\n---> Package not successfully installed; cleaning up..."
            rm -rf ${install_location}
        fi
    else
        echo "\n---> User declined to install; cleaning up..."
        rm -rf ${install_location}
    fi

    # Change directory back, or else git will give a "fatal: unable to read
    # current working directory" error
    cd

    return 0
}

remove_aur_package() {
    declare -r pkg=$1

    if ! pacman -Q ${pkg} &> /dev/null; then
        echo "${ERROR} package is not installed on system"
        exit 1
    fi

    if [[ ! -d ${program_cache}/${pkg} ]]; then
        echo "${WARNING} package is not in ${program_cache}"
    else 
        echo "---> Removing ${program_cache}/${pkg}..."
        rm -rf ${program_cache}/${pkg}
    fi
    
    sudo pacman -Rns ${pkg}

    return 0
}

# main: centralizezd place to run all functions of the program
main() {
    initialization_and_sanitization

    declare operation=$1

    # Process options
    case ${operation} in
        -h )
            display_help_message
            ;;

        -v )
            echo "Version: ${VERSION}"
            ;;

        install )
            shift # remove subcommand
            declare pkgs=$@
            
            # Error checking
            if [[ -z ${pkgs} ]]; then 
                echo "${ERROR} no package specified" &&
                exit 1
            else
                shift
            fi

            for pkg in ${pkgs}; do
                install_aur_package ${pkg}
            done
            ;;

        search )
            shift # remove subcommand
            declare pkgs=$@

            # Error checking 
            if [[ -z ${pkgs} ]]; then 
                echo "${ERROR} no package specified" &&
                exit 1
            else
                shift
            fi
            search_packages_in_aur ${pkgs}
            ;;

        update )
            shift
            if [[ ! -z $1 ]]; then
                echo "${WARNING} the 'update' operation takes no arguments"
            fi

            update_aur_package_list "v"
            ;;

        remove ) 
            shift
            declare pkgs=$@

            # More error checking...
            if [[ -z ${pkgs} ]]; then
                echo "${ERROR} no package specified" &&
                exit 1
            else 
                shift
            fi

            for pkg in ${pkgs}; do
                remove_aur_package ${pkg}
            done
            ;;

        * )
            echo "${ERROR} no operation specified (use -h for help)"
            exit 1
            ;;
    esac

    exit 0
}

main $COMPLETE_ARGS_LIST
